image: docker:stable

stages:
  - package
  - test-package

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

docker-build-development:
  stage: package
  variables:
    DOCKER_HUB_IMAGE: ${DOCKER_HUB_USER}/${CI_PROJECT_NAME}
  only:
    - branches
  except:
    - master
  script:
    - >
      docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-latest
      -t ${DOCKER_HUB_IMAGE}:${CI_COMMIT_SHA} -t ${DOCKER_HUB_IMAGE}:${CI_COMMIT_REF_NAME}-latest .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}
    - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
    - docker push ${DOCKER_HUB_IMAGE}

docker-build-stable:
  stage: package
  variables:
    DOCKER_HUB_IMAGE: ${DOCKER_HUB_USER}/${CI_PROJECT_NAME}
  only:
    - master
  script:
    - >
      docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -t ${CI_REGISTRY_IMAGE}:latest
      -t ${DOCKER_HUB_IMAGE}:${CI_COMMIT_SHA} -t ${DOCKER_HUB_IMAGE}:latest .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}
    - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
    - docker push ${DOCKER_HUB_IMAGE}

container-scanning:
  stage: test-package
  allow_failure: true
  only:
    - branches
  script:
    - docker run -d --name db arminc/clair-db:latest
    - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1
    - apk add -U wget ca-certificates
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    - mv clair-scanner_linux_amd64 clair-scanner
    - chmod +x clair-scanner
    - touch clair-whitelist.yml
    - >
      ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-sast-container-report.json -l clair.log
      -w clair-whitelist.yml ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} || true
  artifacts:
    paths: [gl-sast-container-report.json]
